create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null,
  badge text not null,
  image_url text not null,
  highlight text not null,
  price_cents integer not null check (price_cents > 0),
  sort_order integer not null default 1,
  is_active boolean not null default true,
  created_at timestamp with time zone default now()
);

alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products
for select
using (true);

insert into public.products (name, slug, description, badge, image_url, highlight, price_cents, sort_order)
values
  (
    'Blazer Nova Sable',
    'blazer-nova-sable',
    'Blazer oversize structure, drape impeccable et coupe editoriale pour un look premium.',
    'Best seller',
    'https://image.pollinations.ai/prompt/ai%20generated%20fashion%20photo%20beige%20oversized%20blazer%20studio%20lighting%20high%20detail',
    'Finition tailleur italienne',
    14900,
    1
  ),
  (
    'Pantalon Flux Creme',
    'pantalon-flux-creme',
    'Pantalon taille haute fluide avec tombant net pour journee active et soiree chic.',
    'Nouveau',
    'https://image.pollinations.ai/prompt/ai%20generated%20fashion%20photo%20cream%20wide%20leg%20pants%20minimal%20studio%20shoot',
    'Confort premium toute saison',
    8900,
    2
  ),
  (
    'Trench Aura Cacao',
    'trench-aura-cacao',
    'Trench long en gabardine legere, volume moderne et details couture pour une silhouette forte.',
    'Edition limitee',
    'https://image.pollinations.ai/prompt/ai%20generated%20fashion%20photo%20dark%20brown%20trench%20coat%20runway%20style',
    'Piece statement de la capsule',
    17900,
    3
  )
on conflict (slug)
do update set
  name = excluded.name,
  description = excluded.description,
  badge = excluded.badge,
  image_url = excluded.image_url,
  highlight = excluded.highlight,
  price_cents = excluded.price_cents,
  sort_order = excluded.sort_order,
  is_active = true;
